from openpyxl import Workbook

wb = Workbook()

turmas = ["2A","2B","2C","2D","3A","3B","3C","3D"]

# LISTA DE ALUNOS POR TURMA (edite conforme necessário)
alunos_por_turma = {
    "2A": [
    "ABNER ALMEIDA ESCALANTE BARBOZA",
    "AMANDA GONÇALVES REFOSCO DA SILVA",
    "AMANDA ZADI GONZALES",
    "ANA CAROLINA EUSTÁCHIO PADILHA",
    "ANTHONY AJALA RAMOS",
    "BIANCA SILVA BOAVENTURA",
    "CLARA CHIARAPA MADUREIRA DE PINHO",
    "EDUARDO ALBUQUERQUE RAMOS",
    "EMANUELLY DOS SANTOS NASCIMENTO BATISTA DE MELO",
    "EMILIANO MEJIA JIMENEZ",
    "FELIPE PILEGI DIB",
    "FERNANDA FLORENCIO BATISTA",
    "FERNANDA MOTTA ALDROVANDI",
    "GUILHERME STIEGEMEIER DE SOUZA",
    "JHULLIANY MEIRELES ANTUNES",
    "JOÃO VICTOR VIEIRA PACINI",
    "JULIA NOVAES FILES",
    "JULIA VASQUES FERRAZ",
    "KARINA MARTINS DA SILVA",
    "KAWANY DANIELLY DA SILVA FERREIRA",
    "LIVIA ROCHA CLAUDINO",
    "LUCAS VENERUCHI MARINHO VALADARES",
    "MARCOS ANDRÉ REYES DE OLIVEIRA",
    "MARESSA EDUARDA DE SOUZA ZANIN",
    "MARIA FERNANDA BARBOSA FONTOURA",
    "MARIA LUIZA ELISEI BERNARDO",
    "MAYARA BARBOSA MENDES",
    "NICKOLAS DE SOUZA GAUNA",
    "RAFAELA DAMAZIO ORTEGA MARINO",
    "RAIKE PAES FERNANDES DE FREITAS",
    "RAPHAELA BEZERRA NUNES",
    "SAMIR DA SILVA CARDENA",
    "SOFIA MONTEIRO DE FREITAS",
    "VITOR LOPES SGOBBI MOREIRA",
    "WALLENTINA DANIELA BATALHA SANT'ANA",
    "YOHAN VICTOR FRANCHINI RAMOS",
    "MARIA ISABELA ARAUJO GONÇALVES RUIZ"
],
    "2B": [
    "ANA CAROLINA BRITO DA SILVA",
    "ANA KAROLYNA ALMADA COIMBRA",
    "ANA LUIZA RODRIGUES SANDIM",
    "ANGELINA SOUZA LIMA",
    "BEATRIZ RODA SCARIOT",
    "BIANCA DE OLIVEIRA PROENÇA",
    "BRYAN FELIPE MENDES SANTOS SILVA",
    "CARLOS EDUARDO HEISLER RODRIGUES",
    "DANIEL FELIX AUDI",
    "GABRIELA DA SILVA PEREIRA",
    "GABRIEL ALMIRO PEREIRA FOGAÇA",
    "GIOVANA GARCIA FERREIRA",
    "GIOVANNA QUEIROZ ESCALANTE SANT'ANA",
    "GUSTAVO HENRIQUE DOS SANTOS BENITES",
    "ISABELLI BARBOSA SCHABARUM",
    "JOSÉ RUBENS FIGUEIRA NETO",
    "LAÍS DE FARIAS RAMOS",
    "LAURA DANTAS DE SOUZA",
    "LUIS GUSTAVO GOMES VAZ DA SILVA (T-04/03/2026)",
    "LUIZ GUSTAVO PACHE SALLES",
    "MARIA CLARA DE DEUS SMITH",
    "MARIA EDUARDA CRISTALDO DUARTE",
    "MARIA EDUARDA MARINHO DE FRANÇA",
    "MARIA LUIZA DA SILVA ALVES",
    "MATEUS MAIA BATISTOTI OKUMOTO",
    "MIGUEL DE SOUZA GONÇALVES",
    "MYLENA NEVES DE PAULA",
    "NICOLLY DOS SANTOS DA SILVA",
    "RENATA SOARES SOUZA",
    "ROBSON BARROS DA SILVA",
    "SOPHIA LOPES RODRIGUES",
    "VINICIUS PEREIRA MARQUES",
    "VITÓRIA GABRIELE DIAS DE ANDRADE",
    "VITÓRIA SILVA FREITAS (T-05/03/2026)",
    "YAGO COELHO DE REZENDE",
    "RAFAELLA MORAIS BRAMBILLA (RM-13/03/2026 para 2º Ano C -BIG DATA)",
    "THEO FAGUNDES DA SILVA"
],
    "2C": [
    "ÁGATA THALITA PACHECO DA SILVA SOUZA",
    "ALEXANDRE DURAN DA SILVA",
    "ANTHONNY RICARDO CARDOSO DE SOUZA",
    "ANTONIO LUIZ FRAGA MOREIRA NETO",
    "ARTHUR EVANGELISTA DE SOUZA QUEVEDO",
    "BEATRIZ MOREIRA DE FREITAS",
    "BRENO ANUNCIAÇÃO ADORNO",
    "CARLOS MAGNO DA LUZ ANIZ",
    "CHARLES JOAQUIM SILVA BARROS",
    "EMANUEL DA SILVA SANTOS",
    "FERNANDA SABIONI RIBAS",
    "GIOVANA MAIA ALVES",
    "GIOVANNA DA SILVA ANDRADE",
    "GUILHERME LACERDA DE LIMA",
    "HEITOR DORNELES DE ARAÚJO",
    "ISABELLA RODRIGUES GODINHO",
    "ISAQUE CAMPOS MOREIRA ZALEWSKI",
    "IZABELA CRISTALDO REZENDE",
    "JULIA PUERTAS LOPES",
    "JULIA YASMIM DE SOUZA LEÃO",
    "LUISA FONSECA GOMES",
    "LUIZ FERNANDO GAEDICKE",
    "MARIA ISABELA ARAUJO GONÇALVES RUIZ (RM-01/04/2026 para 2º Ano A -CHS)",
    "MARIA VITORIA SOUZA DA SILVA",
    "PEDRO HENRIQUE COSTA DIAS",
    "RENATO CAMPOS ROHVEDDER",
    "ROBERT MENEGON TORRES GONZALEZ",
    "THEO FAGUNDES DA SILVA (RM-25/03/2026 para 2º Ano B -CHS)",
    "VALENTINA TEIXEIRA PAGNONCELLI",
    "RAFAELLA MORAIS BRAMBILLA",
    "ISADORA PAGANOTTO FERREIRA"
],
    "2D": [
    "ANA CLARA DE ARRUDA RODRIGUES",
    "ARTHUR DOS SANTOS DE BRUM",
    "ARTHUR TEODORO BORGES",
    "BIANCA BARBOSA OLIVEIRA",
    "BRENO HENRIQUE SOUZA OLIVEIRA DA SILVA",
    "DAVI PORSCH SILVA",
    "EMILLY STEPHANNY ACOSTA FERREIRA",
    "GIANLUCA SOUZA CLARANHAN",
    "GIULIA CRISTINA MONSON DE PAULA",
    "HEITOR DE LIMA BARBOSA",
    "ISABELA ROSA BENITES DE MARIA",
    "ISABELLA APARECIDA SANTOS BORGES",
    "ISABELLE BATISTOTI DEVES",
    "ISABELLY SANTOS FERREIRA",
    "ISADORA DA SILVA MEDINA",
    "ISADORA LOLA SANTOS DE LARA",
    "JOÃO PEDRO CORRÊA DE OLIVEIRA LEWERGGER",
    "JOÃO VITOR CAMARGO DO CARMO",
    "JULIANA CORREA RABELO",
    "KALINDA KAUANNY RAMOS DOS SANTOS",
    "LETÍCIA BERGAMASCHI LOPES",
    "LYVIA DA SILVA SANTOS",
    "MARCOS ALENCAR ANDRADE CARNEIRO",
    "NICOLLY AUXILIADORA CONTRERA PEIXOTO",
    "RAFAELA CAMPOS MAIDANA",
    "RIAN SILVA GARCIA (T-03/03/2026)",
    "SAMUEL KEI DA CONCEIÇÃO MORI",
    "SOPHIA MITZKO DE BRITO",
    "THEO ACOSTA",
    "VINÍCIUS LEITE DINIZ",
    "VITÓRIA MIKAELLY ANCEL ARAGÃO",
    "VITÓRIA NASCIMENTO BRANDÃO",
    "LAVÍNYA ALVES RIBEIRO"
],
    "3A": [
    "ANA ALÍCIA URBIETA DA COSTA MARTINS",
    "ANA JULIA ALVES PAGANOTTI",
    "ANNY LUIZA GOES DE OLIVEIRA",
    "ARTUR GAIOSO GUIMARÃES DE OLIVEIRA",
    "ASTÚRIO DE MATOS OZÓRIO NETO",
    "AXEL AUGUSTO SANTOS SILVA",
    "GABRIEL FANTINI DE SOUZA",
    "GABRIELLA CARVALHO DE LIMA",
    "GENI KERYLLIN ROCHA DA SILVA",
    "HÉLIO ANTONIO ZARA DE SOUZA JÚNIOR",
    "JOÃO FELIPE COSMO FREITAS",
    "JOÃO GUILHERME NOCKO MONGES (T-10/03/2026)",
    "JOSÉ HENRIQUE SANCHES CÂNDIDO",
    "JÚLIA SANTOS DIAS",
    "KAIQUE KOLTERMANN REZENDE",
    "KELVIN HENRIQUE DE OLIVEIRA DA SILVA",
    "LAÍS VALVERDE DE FARIA MUZILI",
    "LUCAS DAVI MAGALHÃES DE LIMA",
    "MARCELLA FEIJÓ TALHATTI",
    "MARCO AURELIO SANCHES PAREDES",
    "MARIA EDUARDA MORAES ALENCASTRO",
    "MARIA EDUARDA NEVES LIMA",
    "MARIA VICTÓRIA RIBEIRO LIMA",
    "MÁRIO GALEANO FLORES FILHO",
    "MATHEUS GONÇALVES GOMES",
    "MURILO ALVES RIBEIRO AGOSTINHO",
    "MURILO SCHMIDT SOZZA",
    "NICOLAS FLORES AMARAL",
    "PABLO DOMINGUEZ DOS SANTOS",
    "PAULO HENRIQUE SOUZA DE MENDONÇA",
    "PEDRO HENRIQUE LEAL GENOBIE DA COSTA",
    "PEDRO HENRIQUE PAES MIGUEL",
    "RAFAEL AUGUSTO BRITEZ GONSALES",
    "RAFAEL ORTIZ FREITAS",
    "SAMUEL DA ROCHA BARBOSA",
    "STEFFANY PEREIRA BATHEL NEVES",
    "VÍTOR HUGO ARAUJO FEDRIZZI",
    "MONIQUE BORGO VALENCIA"
],
    "3B": [
    "AMANDA RODRIGUES LEOPOLDINO (T-01/04/2026)",
    "ANA CLARA LEONEL MOREIRA DE OLIVEIRA",
    "ANA JULIA ROMBI VIANA",
    "DAVI PORTUGAL CARAMELO",
    "DAVI SENA PORCINGULA RODRIGUES",
    "DÓROTHY BEATRIZ CORRÊA AMARAL",
    "EDUARDO CARDOSO SILVA",
    "ENZO CAMPOS TOGNINI",
    "FÁBIO HENRIQUE SANTOS DE OLIVEIRA SANT'ANA",
    "FELLIPE FAGUNDES DA SILVA",
    "GEOVANA PADILHA SANTOS",
    "HEITOR POMATTI FARIA",
    "HELLENA CÉSPEDES LOUREIRO",
    "ISABELE MENDES GUTIERRES",
    "ISABELLY SILVA MOREIRA",
    "JOÃO FELIPE CARVALHO ARAUJO",
    "JOÃO RAFAEL FRANÇA DA LUZ",
    "JULIA KOLTERMANN MIRANDA",
    "JULIAN GARIBALDI DE BRITO",
    "KETLEN GABRIELA COELHO MACHADO",
    "LARA SCATOLIN ROSSATTI",
    "LÍVIA DOS SANTOS MARTINS",
    "LUCAS VINICIUS NOGUEIRA DE PAIVA",
    "LUÍS FELIPE MAZZEO",
    "LUIZ ROBERTO FRANCO DUARTE",
    "MARIA CLARA GARCIA ALVES",
    "MARIANA ARANTES DINIZ",
    "PEDRO HENRIQUE RODRIGUES VILLARINO",
    "PEDRO OTÁVIO OLIVEIRA GARCIA",
    "ROBSON GABRIEL DE SOUZA DORNELES",
    "SABRINA PIRES DE SOUSA",
    "SÂMIA DE OLIVEIRA ZACARIAS",
    "SOFIA DE SOUZA BERNARDO",
    "SOPHIA MARIA MACIEL DA SILVA",
    "VICTORIA ADERNO VASCONCELOS",
    "YASMIN LOUREIRO DO NASCIMENTO",
    "MARIA LUIZA MARQUES MANGINI"
],
    "3C": [
    "ALICE MOREIRA RODRIGUES",
    "ALICIA MALDONADO TRENTINI",
    "AMANDA LIMA DE SOUSA",
    "AMANDA MOURA DE FREITAS",
    "AMAPOLA GIULIA GOMES BENDER SANTOS",
    "ANA LUISA ANDRADE ÁVILA",
    "ANGELINA NOGUEIRA BRANDÃO",
    "ANY BEATRICI PINHEIRO GAMA",
    "APOLO VERDIN SALES DE MOURA CAMPOS",
    "ARIEL ARAUJO JUNIOR",
    "CAUEH GRESSLER DE MEIRA",
    "DANIELA MARTIN ANDRADE",
    "DANIEL ARECO CORDEIRO",
    "EDUARDO HENRIQUE SANTOS NUNES",
    "EVELYN DA SILVA ROCHA",
    "GABRIELA CARAMALAC CRUZ",
    "GUILHERME DA SILVA BRITEZ",
    "GUILHERME MIRANDA DOS SANTOS",
    "GUILHERME NUNES FERREIRA",
    "GUSTAVO COSTA SOARES",
    "IAGO RYUJI ONISHI MIRANDA",
    "ISABELA BENITES MADUREIRA DE PINHO",
    "ISABELLA LETÍCIA FERREIRA DA SILVA",
    "ISABELY ROSSETTINI BAGNOLI COSTA",
    "JOÃO LUCAS LOPES BARCELOS",
    "JOSÉ EDUARDO NEVES DA SILVA",
    "KAMYLLY MARCELLY FLORENTIN LEAL",
    "LARA AYUMI ONISHI MIRANDA",
    "LARA VITÓRIA COELHO SANCHES",
    "LIA MARYELLEN ESPINDOLA ROCHA",
    "LUCAS DE OLIVEIRA PEREIRA (T-10/03/2026)",
    "LUCAS LACERDA PASSOS",
    "MELISSA DA SILVA FEITOZA",
    "NICOLLY FIGUEIREDO PECOIS",
    "RAIANY RIBEIRO DE SOUZA",
    "YASMIN PEREIRA SOUZA",
    "ISABELA SARTORIO DA SILVA"
],
    "3D": [
    "ALEXANDRE DA COSTA BARBOSA",
    "ANA JULIA GOMES CORSINO SILVA",
    "ANDRÉ DE ALMEIDA MATIAS",
    "ARTHUR DA SILVA FERREIRA",
    "BEATRIZ ANDRADE DOS SANTOS",
    "CARLOS EDUARDO FAGUNDES LOPES",
    "EDUARDA MORAES DE PAIVA",
    "FERNANDA VIEIRA FERNANDES",
    "GILBERTO CURY GUIMARÃES BEGENA",
    "HEROS VINICIUS ALMEIDA CABRAL DOS SANTOS CANDIDO",
    "ISABELA SARTORIO DA SILVA (RM-12/03/2026 para 3º Ano C -LGG)",
    "JOAQUIM CEMIN CAÇÃO",
    "JORGE LUIS MACIEL TOLEDO",
    "JOSÉ VICTOR ORTIZ PHELIPPE",
    "JULIA EDUARDA DE OLIVEIRA BRUM SCHER TAVARES",
    "KALLYL HÉBANO JARA DE SOUZA",
    "LAYANI ARAÚJO DE LIMA",
    "LETÍCIA RODRIGUES DE AQUINO LIMA",
    "MARIA LUIZA MARQUES MANGINI (RM-17/03/2026 para 3º Ano B -LGG)",
    "MARIA PAULA GOMES CORSINO SILVA",
    "MONIQUE BORGO VALENCIA (RM-11/03/2026 para 3º Ano A -LGG)",
    "NICOLLY DOMINGOS DE ARAUJO",
    "OTÁVIO BRAGA DIONIZIO MARTINS",
    "PAULO RICARDO BARBOSA PINHEIRO",
    "PEDRO HENRIQUE SILVA DE OLIVEIRA",
    "PIETRO QUINTANA (T-10/03/2026)",
    "RAKEL BARBOSA DA SILVA",
    "RIQUELME BORDES BRANDÃO",
    "THIAGO DOS SANTOS NOGUEIRA FILHO",
    "THIAGO GABELONI PEREZ BALBERDE",
    "VINÍCIUS MITZKO DE BRITO",
    "VITOR COSTA DAMAZIO",
    "VITOR DA SILVA FERREIRA",
    "GIOVANA DE SOUZA DELECLODI"
] 
}

for i, turma in enumerate(turmas):
    if i == 0:
        ws = wb.active
        ws.title = turma
    else:
        ws = wb.create_sheet(title=turma)
    
    # Cabeçalhos com N4 e média para cada bimestre
    headers = [
        "Nome",
        "N1_B1","N2_B1","N3_B1","N4_B1","Atv1_B1","Atv2_B1","Media_B1",
        "N1_B2","N2_B2","N3_B2","N4_B2","Atv1_B2","Atv2_B2","Media_B2",
        "N1_B3","N2_B3","N3_B3","N4_B3","Atv1_B3","Atv2_B3","Media_B3",
        "N1_B4","N2_B4","N3_B4","N4_B4","Atv1_B4","Atv2_B4","Media_B4",
        "Media_Anual","Status"
    ]
    
    ws.append(headers)
    
    lista_nomes = alunos_por_turma.get(turma, [])
    
    for row, nome in enumerate(lista_nomes, start=2):
        ws.cell(row=row, column=1, value=nome)
        
        medias_bimestrais = []

        for b in range(4):
            # 7 colunas por bimestre (N1, N2, N3, N4, Atv1, Atv2, Media)
            col_base = 2 + b*7
            
            n1 = ws.cell(row=row, column=col_base).coordinate
            n2 = ws.cell(row=row, column=col_base+1).coordinate
            n3 = ws.cell(row=row, column=col_base+2).coordinate
            n4 = ws.cell(row=row, column=col_base+3).coordinate
            atv1 = ws.cell(row=row, column=col_base+4).coordinate
            atv2 = ws.cell(row=row, column=col_base+5).coordinate
            
            media_cell = ws.cell(row=row, column=col_base+6)
            
            # --- FÓRMULA DO BIMESTRE ---
            # 1. Pega as 2 maiores notas de N1, N2 e N3 e soma com N4
            # 2. Divide por 3
            # 3. Soma com Atividades
            # 4. Arredonda usando MROUND para intervalos de 0.5 (sua regra de proximidade)
            formula_notas = f"((LARGE({n1}:{n3},1)+LARGE({n1}:{n3},2)+{n4})/3)"
            formula_total = f"({formula_notas}+{atv1}+{atv2})"
            
            media_cell.value = f"=IFERROR(MIN(MROUND({formula_total}, 0.5), 10), 0)"
            
            medias_bimestrais.append(media_cell.coordinate)
        
        # --- MÉDIA ANUAL (Coluna 30) ---
        m1, m2, m3, m4 = medias_bimestrais
        media_anual = ws.cell(row=row, column=30)
        
        # Média progressiva (ignora bimestres com valor 0)
        formula_media_prog = (
            f'IF({m2}=0,{m1},'
            f'IF({m3}=0,AVERAGE({m1},{m2}),'
            f'IF({m4}=0,AVERAGE({m1},{m2},{m3}),'
            f'AVERAGE({m1},{m2},{m3},{m4}))))'
        )
        
        media_anual.value = f"=MROUND({formula_media_prog}, 0.5)"
        
        # --- STATUS FINAL (Coluna 31) ---
        status = ws.cell(row=row, column=31)
        status.value = f'=IF({media_anual.coordinate}>=6,"Aprovado","Exame")'

# Salvar o arquivo
# file_path = r"C:\Users\capta\Desktop\ANO 2026\planilha_turmas_final.xlsx"
file_path = r"C:\Users\JowilsonNunes\Documents\GitHub\Meus-Projetos\planilha_turmas_final.xlsx"
wb.save(file_path)

print("Planilha gerada com sucesso!")